version: "3.1"
services:
  spotify_tracker_api:
    container_name: spotify_tracker_api
    image: spotify_tracker_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./test/params:/app/params
      - ./params/params_dev.ini:/app/params/params.ini
      - ./test/logs:/app/logs
      - ./test/data:/app/data
      - ./spotify_tracker_api.py:/app/spotify_tracker_api.py
      - ./spotify_api_helpers.py:/app/spotify_api_helpers.py
      - ./logger_utils.py:/app/logger_utils.py
      - ./ws_manager.py:/app/ws_manager.py
      - ./rss_feed_generator.py:/app/rss_feed_generator.py
      - ./params_utils.py:/app/params_utils.py
      - ./templates/artists.html.j2:/app/templates/artists.html.j2
      - ./templates/releases.html.j2:/app/templates/releases.html.j2
      - ./templates/shows.html.j2:/app/templates/shows.html.j2
      - ./templates/episodes.html.j2:/app/templates/episodes.html.j2
      - ./templates/landing_page.html.j2:/app/templates/landing_page.html.j2
      - ./templates/rss_feed.xml.j2:/app/templates/rss_feed.xml.j2
      - ./static/style.css:/app/static/style.css
      - ./static/engine.js:/app/static/engine.js
      - ./entrypoint.sh:/app/entrypoint.sh
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DEBUG=DEBUG
